<?php

/**
 * @file
 * Holds hooks for the Color API module.
 */

 /**
  * Implements hook_theme().
  */
function colorapi_theme($existing, $type, $theme, $path) {

  return [
    'colorapi_color_display' => [
      'variables' => [
        'delta' => NULL,
        'item' => NULL,
        'hexadecimal_color' => NULL,
      ],
      'template' => 'colorapi-color-display',
    ],
    'colorapi_text_display' => [
      'variables' => [
        'delta' => NULL,
        'item' => NULL,
        'hexadecimal_color' => NULL,
      ],
      'template' => 'colorapi-text-display',
    ],
  ];
}
