colorapi.settings:
  type: config_object
  label: 'Colora API module settings'
  mapping:
    enable_color_field:
      type: boolean
      label: 'Whether or not the Color Field should be enabled'
    enable_color_entity:
      type: boolean
      label: 'Whether or not the Color Entity should be enabled'

colorapi.colorapi_color.*:
  type: config_entity
  label: 'Color entity configuration'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    color:
      type: hexadecimal_color
      label: 'The color, in hexadecimal format'

field.value.colorapi_color_field:
  type: mapping
  label: 'Color Field Default value'
  mapping:
    name:
      type: string
      label: 'Human-readable color name'
    color:
      type: hexadecimal_color
      label: 'The color in hexadecimal format'

field.formatter.settings.colorapi_raw_hex_display:
  type: mapping
  label: 'Raw Hexadecimal Color display formatter settings'
  mapping:
    display_name:
      type: boolean
      label: 'Display the human-readable name in the field output'
    show_hash:
      type: boolean
      label: 'Prefix colors with the hash (#) symbol'

field.formatter.settings.colorapi_text_display:
  type: mapping
  label: 'Text Color display formatter settings'
  mapping:
    display_name:
      type: boolean
      label: 'Display the human-readable name in the field output'
    show_hash:
      type: boolean
      label: 'Prefix colors with the hash (#) symbol'

field.formatter.settings.colorapi_raw_rgb_display:
  type: mapping
  label: 'Raw RGB display formatter settings'
  mapping:
    display_name:
      type: boolean
      label: 'Display the human-readable name in the field output'

field.formatter.settings.colorapi_color_display:
  type: mapping
  label: 'Colored Block display formatter settings'
  mapping:
    display_name:
      type: boolean
      label: 'Display the human-readable name in the field output'
