colorapi_color:
  label: 'Color'
  class: '\Drupal\colorapi\Plugin\DataType\ColorData'
  definition_class: '\Drupal\colorapi\TypedData\Definition\ColorDefinition'

hexadecimal_color:
  label: 'Hexadecimal Color String'
  class: '\Drupal\colorapi\Plugin\DataType\HexColorData'

rgb_color:
  label: 'RGB Color'
  class: '\Drupal\colorapi\Plugin\DataType\RgbColorData'
  definition_class: '\Drupal\colorapi\TypedData\Definition\RgbColorDefinition'
